### ISSUE TITLE
Bug memory.js

### ISSUE THREAD

**Issue by GunsterxD** [techpines/express.io#6]
I'm using the express.io, but when when I create any session and turn off the server and turn it back to this error happens:
/var/www/stoponline/servidor/node_modules/express.io/node_modules/connect/lib/middleware/session/memory.js:46
      expires = 'string' == typeof sess.cookie.expires
                                              ^
TypeError: Cannot read property 'expires' of undefined
    at /var/www/stoponline/servidor/node_modules/express.io/node_modules/connect/lib/middleware/session/memory.js:46:47
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
Only on the second time that solves!
When no session recorded the error does not occur!

**Comment by techpines** [comment]
Have you taken a look at the session example:

https://github.com/techpines/express.io/tree/master/examples#sessions

My thought is that maybe you are not setting up the sessions properly:

``` js
app.use(express.cookieParser())
app.use(express.session({secret: 'monkey'}))
```

If you are still having issues, then try throwing up a little more code and I'll see if I can't figure out what your problem is.

**Comment by techpines** [comment]
Also, make sure you are using the latest version, 1.1.8.
